{
  "comments": [
    {
      "key": {
        "uuid": "ca9cd539_7b6b7947",
        "filename": "tools/libcore_failures.txt",
        "patchSetId": 1
      },
      "lineNbr": 224,
      "author": {
        "id": 1052644
      },
      "writtenOn": "2018-04-19T18:08:57Z",
      "side": 1,
      "message": "Actually, could you move that to tools/libcore_network_failures.txt?",
      "range": {
        "startLine": 218,
        "startChar": 0,
        "endLine": 224,
        "endChar": 1
      },
      "revId": "00cd172a88772da0272d565a4365b586b6393faf",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": true
    }
  ]
}