{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "9353d446_40d497fd",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 5
      },
      "lineNbr": 0,
      "author": {
        "id": 1042828
      },
      "writtenOn": "2021-05-30T02:04:22Z",
      "side": 1,
      "message": "I still don\u0027t understand how this failure is possible. Retrying with more diagnostic output.",
      "revId": "04b31525b6ec9e0beb1455ad560e800146800c05",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}