{
  "comments": [
    {
      "key": {
        "uuid": "2a250e5f_3520a43a",
        "filename": "runtime/verifier/reg_type.cc",
        "patchSetId": 2
      },
      "lineNbr": 717,
      "author": {
        "id": 1038443
      },
      "writtenOn": "2017-07-21T09:05:03Z",
      "side": 1,
      "message": "Add a comment why you\u0027re not dealing with the exception here?",
      "revId": "271624675de94b2d26f0d35072c32b5c18042cfd",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "cca49abf_075cefd9",
        "filename": "runtime/verifier/reg_type.cc",
        "patchSetId": 2
      },
      "lineNbr": 765,
      "author": {
        "id": 1038443
      },
      "writtenOn": "2017-07-21T09:05:03Z",
      "side": 1,
      "message": "Comment? What do do with the exception?",
      "revId": "271624675de94b2d26f0d35072c32b5c18042cfd",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    }
  ]
}