{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "f6894895_908e4bd3",
        "filename": "/COMMIT_MSG",
        "patchSetId": 2
      },
      "lineNbr": 11,
      "author": {
        "id": 1018108
      },
      "writtenOn": "2023-09-13T13:01:16Z",
      "side": 1,
      "message": "Is there a new bug, or should this be under b/37272822 as indicated by the section in known failures?",
      "revId": "98a63f037513290694bb8b12c24023aa190cc645",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}