{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "dae59f69_5a9a26c2",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1018108
      },
      "writtenOn": "2021-11-08T17:00:21Z",
      "side": 1,
      "message": "See discussion on bug 205552838 .",
      "revId": "bbcbcfb4233f51e3fc057b6c14676428275dbe7d",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "7d34153d_024973ad",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1876033
      },
      "writtenOn": "2021-11-08T17:07:03Z",
      "side": 1,
      "message": "Thanks, assignign the test failure bug to you as well and abandoning this revert.",
      "parentUuid": "dae59f69_5a9a26c2",
      "revId": "bbcbcfb4233f51e3fc057b6c14676428275dbe7d",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}