{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "28420b6c_18f4bb8b",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1258954
      },
      "writtenOn": "2023-02-02T05:26:27Z",
      "side": 1,
      "message": "The test (in the mentioned bug) is consistently failing since this CL.",
      "revId": "cb7fe7385d27d3086b4075ded4bee5c23d8ae939",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}