Test stopped using breakpoint
Single call with PopFrame on StandardTestObject { cnt: 0 }
result is StandardTestObject { cnt: 2 }
Test stopped using breakpoint with declared synchronized function
Single call with PopFrame on SynchronizedFunctionTestObject { cnt: 0 }
result is SynchronizedFunctionTestObject { cnt: 2 }
Test stopped using breakpoint with synchronized block
Single call with PopFrame on SynchronizedTestObject { cnt: 0 }
result is SynchronizedTestObject { cnt: 2 }
Test stopped on single step
Single call with PopFrame on StandardTestObject { cnt: 0 }
result is StandardTestObject { cnt: 2 }
Test stopped on field access
Single call with PopFrame on FieldBasedTestObject { cnt: 0, TARGET_FIELD: 0 }
result is FieldBasedTestObject { cnt: 2, TARGET_FIELD: 10 }
Test stopped on field modification
Single call with PopFrame on FieldBasedTestObject { cnt: 0, TARGET_FIELD: 0 }
result is FieldBasedTestObject { cnt: 2, TARGET_FIELD: 10 }
Test stopped during Method Exit of doNothing
Single call with PopFrame on StandardTestObject { cnt: 0 }
result is StandardTestObject { cnt: 1 }
Test stopped during Method Enter of doNothing
Single call with PopFrame on StandardTestObject { cnt: 0 }
result is StandardTestObject { cnt: 1 }
Test stopped during Method Exit of calledFunction
Single call with PopFrame on StandardTestObject { cnt: 0 }
result is StandardTestObject { cnt: 2 }
Test stopped during Method Enter of calledFunction
Single call with PopFrame on StandardTestObject { cnt: 0 }
result is StandardTestObject { cnt: 1 }
Test stopped during notifyFramePop without exception on pop of calledFunction
Single call with PopFrame on StandardTestObject { cnt: 0 }
result is StandardTestObject { cnt: 2 }
Test stopped during notifyFramePop without exception on pop of doNothing
Single call with PopFrame on StandardTestObject { cnt: 0 }
result is StandardTestObject { cnt: 1 }
Test stopped during notifyFramePop with exception on pop of calledFunction
Single call with PopFrame on ExceptionThrowTestObject { cnt: 0 }
art.Test1953$ExceptionThrowTestObject$TestError thrown and caught!
result is ExceptionThrowTestObject { cnt: 2 }
Test stopped during notifyFramePop with exception on pop of doThrow
Single call with PopFrame on ExceptionCatchTestObject { cnt: 0 }
art.Test1953$ExceptionCatchTestObject$TestError caught in called function.
result is ExceptionCatchTestObject { cnt: 1 }
Test stopped during ExceptionCatch event of calledFunction (catch in called function, throw in called function)
Single call with PopFrame on ExceptionThrowTestObject { cnt: 0 }
art.Test1953$ExceptionThrowTestObject$TestError caught in same function.
result is ExceptionThrowTestObject { cnt: 2 }
Test stopped during ExceptionCatch event of calledFunction (catch in called function, throw in subroutine)
Single call with PopFrame on ExceptionCatchTestObject { cnt: 0 }
art.Test1953$ExceptionCatchTestObject$TestError caught in called function.
result is ExceptionCatchTestObject { cnt: 2 }
Test stopped during Exception event of calledFunction (catch in calling function)
Single call with PopFrame on ExceptionThrowTestObject { cnt: 0 }
art.Test1953$ExceptionThrowTestObject$TestError thrown and caught!
result is ExceptionThrowTestObject { cnt: 2 }
Test stopped during Exception event of calledFunction (catch in called function)
Single call with PopFrame on ExceptionThrowTestObject { cnt: 0 }
art.Test1953$ExceptionThrowTestObject$TestError caught in same function.
result is ExceptionThrowTestObject { cnt: 2 }
Test stopped during Exception event of calledFunction (catch in parent of calling function)
Single call with PopFrame on ExceptionThrowFarTestObject { cnt: 0 }
art.Test1953$ExceptionThrowFarTestObject$TestError thrown and caught!
result is ExceptionThrowFarTestObject { cnt: 2 }
Test stopped during Exception event of calledFunction (catch in called function)
Single call with PopFrame on ExceptionThrowFarTestObject { cnt: 0 }
art.Test1953$ExceptionThrowFarTestObject$TestError caught in same function.
result is ExceptionThrowFarTestObject { cnt: 2 }
Test stopped during a ClassLoad event.
Single call with PopFrame on ClassLoadObject { cnt: 0, curClass: 0}
TC0.foo == 1
result is ClassLoadObject { cnt: 2, curClass: 1}
Test stopped during a ClassPrepare event.
Single call with PopFrame on ClassLoadObject { cnt: 0, curClass: 1}
TC1.foo == 2
result is ClassLoadObject { cnt: 2, curClass: 2}
Test stopped during random Suspend.
Single call with PopFrame on SuspendSuddenlyObject { cnt: 0 }
result is SuspendSuddenlyObject { cnt: 2 }
Test redefining frame being popped.
Single call with PopFrame on RedefineTestObject { states: [] current: ORIGINAL }
result is RedefineTestObject { states: [ORIGINAL, REDEFINED] current: REDEFINED }
